- vmware_deploy_ovf:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ vmware_datastore }}'
    cluster: '{{ vmware_cluster }}'
    datastore: '{{ vmware_datacenter }}'
    name: '{{ vm_name }}'
    networks: "{u'VM Network':u'{{ vmware_network }}'}"
    validate_certs: no
    power_on: no
    ovf: '{{ ova_path_loc }}'
  delegate_to: localhost
