- hosts: masters[0]
  vars:
    application_name: coolstore
    lifecycle: dev
    image: cart
    tag_from: latest
    tag_to: dev
  tasks:
  - name: Tag Image
    command: "oc tag {{ image }}:{{ tag_from }} {{ image }}:{{ tag_to }} -n {{ application_name }}"

