---
- name: Verify Yum Repositories and NFS Shared Volumes on Hosts
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Listing the repositories on the bastion host
      shell: yum repolist
      register: getrepolist
    - debug: var=getrepolist.stdout_lines
    - name: List atomic-openshift-node package on all nodes.
      yum:
        list: atomic-openshift-node
      register: getnodeinfo
    - debug: var=getnodeinfo.results
    - name: Display NFS server to see which NFS volumes are shared
      shell: mount -a