- hosts: all
  tasks:
  - name: Download helpernode iso file
    get_url:
      url: "{{ webserver_url }}/{{ iso_name }}"
      dest: "/opt/{{ iso_dir_loc }}/{{ iso_name }}"
  - name: List /opt directory 
    command: "ls /opt"
    register: dir_out 

  - debug: var={{item}}
    with_items: dir_out.stdout_lines

  - name: Copy file to datastore using delegate_to
    vsphere_copy:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      src:  "/opt/{{ iso_dir_loc }}/{{ iso_name }}"
      datacenter: "{{ datacenter }}"
      datastore: "{{ datastore }}"
      path: "{{ folder_name}}//{{ iso_name }}"
    delegate_to: localhost