- hosts: all
  become: false
  tasks:
  - name: "Download {{ file_name }}"
    get_url:
      url: "{{ webserver_url }}/{{ file_name }}"
      dest: "/tmp/{{ file_name }}"

  - name: "Copy {{ file_name }} to  vcenter datastore"
    vsphere_copy:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: '{{ vm_validate_certs }}'
      src:  "/tmp/{{ file_name }}"
      datacenter: "{{ datacenter }}"
      datastore: "{{ datastore }}"
      path: "{{ folder_name}}/{{ file_name }}"
    delegate_to: localhost