- hosts: all
  tasks:
  - name: Download helpernode iso file
    get_url:
      url: "{{ webserver_url }}/{{ iso_name }}"
      dest: "/tmp/{{ iso_name }}"

  - name: Copy file to datastore using delegate_to
    vsphere_copy:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      src:  "/tmp/{{ iso_name }}"
      datacenter: "{{ datacenter }}"
      datastore: "{{ datastore }}"
      path: "{{ folder_name}}//{{ iso_name }}"
    delegate_to: localhost