- hosts: all
  tasks:
  - name: Download helpernode iso file
    get_url:
      url: "{{ webserver_url }}/{{ iso_name }}"
      dest: "/home/{{user_dir}}/.ansible/tmp/{{ iso_name }}"

  - name: List playbook directory 
    command: "ls /home/{{user_dir}}/.ansible/tmp/"
    register: dir_out 

  - debug:
      msg: Copied iso to {{ item }} 
    with_items: dir_out.stdout_lines

  - name: Copy file to datastore using delegate_to
    vsphere_copy:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      src:  "/home/{{user_dir}}/.ansible/tmp/{{ iso_name }}"
      datacenter: "{{ datacenter }}"
      datastore: "{{ datastore }}"
      path: "{{ folder_name}}/{{ iso_name }}"
    delegate_to: localhost