- name: Remove all openshift vms
  hosts: all
  gather_facts: no

  tasks:
  - name: Removing Bootstrap
    block:
      - name: Get virtual machine info
        vmware_vm_info:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          validate_certs: no
          folder: "/Datacenter/vm/ocp4"
        register: vm_info

      - debug:
          msg: "{{ item.uuid }}"
        with_items:
          - "{{ vm_info.virtual_machines | json_query(query) }}"
        vars:
          query: "[?guest_name=='bootstrap']"

      - name: Poweroff bootstrap virtual machine
        vmware_guest:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          datacenter: "{{ vmware_datacenter }}"
          validate_certs: no
          cluster: "{{ vcenter_cluster }}"
          name: "{{ bootstrap_name }}"
          state: poweredoff
        when: '"{{ bootstrap_name }}" in "{{ vm_info.virtual_machines | json_query(query) }}"'

      - name: Removing bootstrap virtual machine
        vmware_guest:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: no
          cluster: "{{ vcenter_cluster }}"
          name: "{{ bootstrap_name }}"
          state: absent
        when: '"{{ bootstrap_name }}" in  "{{ vm_info.virtual_machines | json_query(query) }}"'

      - name: Poweroff master virtual machines
        vmware_guest:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          datacenter: "{{ vmware_datacenter }}"
          validate_certs: no
          cluster: "{{ vcenter_cluster }}"
          name: "{{ item.name }}"
          state: poweredoff
        when: '"{{ item.name }}" in "{{ vm_info.virtual_machines | json_query(query) }}"'
        loop: "{{ masters }}"

      - name: Removing all master virtual machines
        vmware_guest:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: no
          cluster: "{{ vcenter_cluster }}"
          name: "{{ item.name }}"
          state: absent
        when: '"{{ item.name }}" in  "{{ vm_info.virtual_machines | json_query(query) }}"'
        loop: "{{ masters }}"

  - name: Poweroff all worker virtual machines
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vmware_datacenter }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ item.name }}"
      state: poweredoff
    loop: "{{ workers }}"

  - name: Removing worker virtual machines
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ item.name }}"
      state: absent
    loop: "{{ workers }}"
