- name: Remove all openshift vms
  hosts: all
  gather_facts: no

  tasks:
  - name: Check if bootstrap exists
    vmware_guest_info:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ vmware_datacenter }}"
      name: "{{ bootstrap_name }}"
      schema: "vsphere"
      properties:
        - _moId
    delegate_to: localhost
    register: moid_info

  - name: "Bootstrap status"
    debug:
      msg: "{{ moid_info }}"

  - name: Poweroff bootstrap virtual machine
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vmware_datacenter }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ bootstrap_name }}"
      state: poweredoff


  - name: Poweroff master virtual machines
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vmware_datacenter }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ item.name }}"
      state: poweredoff
    loop: "{{ masters }}"

  - name: Poweroff all worker virtual machines
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vmware_datacenter }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ item.name }}"
      state: poweredoff
    loop: "{{ workers }}"

  - name: Removing bootstrap virtual machine
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ bootstrap_name }}"
      state: absent


  - name: Removing all master virtual machines
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ item.name }}"
      state: absent
    loop: "{{ masters }}"

  - name: Removing worker virtual machines
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ item.name }}"
      state: absent
    loop: "{{ workers }}"
