- name: Remove all openshift vms
  hosts: all
  gather_facts: no

  tasks:
  - name: Poweroff bootstrap virtual machines
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vmware_datacenter }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ bootstrap_name }}"
      state: poweredoff
    loop: "{{ masters }}"

  - name: Poweroff master virtual machines
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vmware_datacenter }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ item.name }}"
      state: poweredoff
    loop: "{{ masters }}"

  - name: Poweroff all worker virtual machines
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vmware_datacenter }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ item.name }}"
      state: poweredoff
    loop: "{{ workers }}"

  - name: Removing all master virtual machines
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ bootstrap_name }}"
      state: absent


  - name: Removing all master virtual machines
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ item.name }}"
      state: absent
    loop: "{{ masters }}"

  - name: Removing worker virtual machines
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ item.name }}"
      state: absent
    loop: "{{ workers }}"
