- name: Remove all openshift vms
  hosts: all
  gather_facts: no

  tasks:
  - name: Get UUID from given VM Name
    block:
      - name: Get virtual machine info
        vmware_vm_info:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          folder: "/Datacenter/vm/ocp4"
        delegate_to: localhost
        register: vm_info

      - debug:
          msg: "{{ item.uuid }}"
        with_items:
          - "{{ vm_info.virtual_machines | json_query(query) }}"
        vars:
          query: "[?guest_name=='bootstrap']"

  - name: Poweroff bootstrap virtual machine
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vmware_datacenter }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ bootstrap_name }}"
      state: poweredoff


  - name: Poweroff master virtual machines
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vmware_datacenter }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ item.name }}"
      state: poweredoff
    loop: "{{ masters }}"

  - name: Poweroff all worker virtual machines
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vmware_datacenter }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ item.name }}"
      state: poweredoff
    loop: "{{ workers }}"

  - name: Removing bootstrap virtual machine
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ bootstrap_name }}"
      state: absent


  - name: Removing all master virtual machines
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ item.name }}"
      state: absent
    loop: "{{ masters }}"

  - name: Removing worker virtual machines
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      cluster: "{{ vcenter_cluster }}"
      name: "{{ item.name }}"
      state: absent
    loop: "{{ workers }}"
