- hosts: all
  tasks:
  - name: reboot {{ inventory_hostname }}"
    shell: sleep 2 && shutdown -r now "Restarting VM"
    async: 1
    poll: 0
    ignore_errors: true
    become: true
  - name: Wait 60 seconds, but only start checking after 30 seconds
    wait_for_connection:
      delay: 30
      timeout: 60