---
- hosts: localhost
  tasks:
  - name: generate htpasswd to login to openshift
    shell: |
      htpasswd -b -c /tmp/passwordFile {{ oc_username }} {{ oc_password }}
    delegate_to: localhost
  - name: generate htpasswd to login to openshift
    shell: |
      cat /tmp/passwordFile
    delegate_to: localhost
    register: passResult
  - name: debug result
    debug: var=passResult.stdout
    verbosity: 2
    delegate_to: localhost
  - name: Save hashed password
    set_fact:
      oc_hashed_password: "{{ passResult.stdout }}"
      cacheable: yes
    delegate_to: localhost
  - name: debug hashed password
    debug:
      msg: "Username: {{ oc_username }} Password: {{ oc_hashed_password.split(':')[1] }}"
    verbosity: 2
    delegate_to: localhost
  - name: "Pass username and password to openshift inventory"
    set_stats:
      data:
        oc_user: "{{ oc_username }}"
        oc_pass: "{{ oc_hashed_password.split(':')[1] }}"
    delegate_to: localhost
