- hosts: all
  vars:
    application_name: coolstore
    lifecycle: dev
  tasks:
  - name: login as super user with token on OpenShift 4
    shell: "oc login --token={{ openshift_token }}  --server={{ openshift_url }} --insecure-skip-tls-verify={{ insecure_skip_tls_verify }}"
    when:
     - openshift_token is defined
     - openshift_token is not none
     - openshift_token|trim() != ""
     - use_oc_login == "True"
    ignore_errors: no

  - name: List Projects
    shell: "oc get projects/{{ application_name }}-{{ lifecycle }}"
    register: oc_get_project
    ignore_errors: true

  - name: 'Create Project'
    command: "oc new-project {{ application_name }}-{{ lifecycle }}"
    when: oc_get_project.rc == 1

  - name: 'Assign Permissions'
    command: "oc policy add-role-to-user system:image-puller system:serviceaccount:{{ application_name }}-{{ lifecycle }}:default -n {{ application_name }}"
