- hosts: masters[0]
  vars:
    application_name: coolstore
    lifecycle: dev
  tasks:
  - name: List Template
    shell: "oc get template/{{ application_name }}"
    register: oc_get_template
    ignore_errors: true
  
  - name: Copy Template
    template:
      src: "templates/{{ application_name }}.yml"
      dest: "/tmp/{{ application_name }}.yml"
    when: oc_get_template.rc == 1
  
  - name: Create Template
    shell: "oc create -f /tmp/{{ application_name }}.yml -n {{ application_name }}-{{ lifecycle }}"
    when: oc_get_template.rc == 1

  # TODO: This should actually check for the application, not just the
  # template existence.
  - name: Deploy Application
    shell: "oc new-app {{ application_name }} -n {{ application_name }}-{{ lifecycle }}"
    when: oc_get_template.rc == 1

