---
- hosts: all
  tasks:
  - name:  Register as auto-subscribe to red hat subscription.
    block:
    - name: Register as auto-subscribe to red hat subscription.
      redhat_subscription:
        state: present
        username: "{{ rhel_username }}"
        password: "{{ rhel_password }}"
        auto_attach: true
    when: registernodes
  - name:  Register as auto-subscribe to red hat subscription.
    block:
    - name: Disable all RHSM repositories
      rhsm_repository:
        name: '*'
        state: disabled
    - name: Enable rhel-7-server-rpms repository
      rhsm_repository:
        name: rhel-7-server-rpms
        state: enabled
    - name: Enable rhel-7-server-extras-rpms repository
      rhsm_repository:
        name: rhel-7-server-extras-rpms
        state: enabled
    - name: Enable rhel-7-server-ose-3.11-rpms repository
      rhsm_repository:
        name: rhel-7-server-ose-3.11-rpms
        state: enabled
    - name: Enable rhel-7-fast-datapath-rpms repository
      rhsm_repository:
        name: rhel-7-fast-datapath-rpms
        state: enabled
      when: "'lb' not in inventory_hostname"
    - name: Enable rhel-7-server-ansible-2.6-rpms repository
      rhsm_repository:
        name: rhel-7-server-ansible-2.6-rpms
        state: enabled
    - name: Enable rhel-7-server-optional-rpms repository
      rhsm_repository:
        name: rhel-7-server-optional-rpms
        state: enabled
    - name: Enable rh-gluster-3-client-for-rhel-7-server-rpms repository
      rhsm_repository:
        name: rh-gluster-3-client-for-rhel-7-server-rpms
        state: enabled
      when:
        - glusterstorage
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: install base packages
      yum:
        name:
        - wget
        - git
        - net-tools
        - bind-utils
        - yum-utils
        - iptables-services
        - bridge-utils
        - bash-completion
        - kexec-tools
        - sos
        - psacct
        state: present
    - name: installing openshift-ansible RPM-based installer
      yum:
        name:
        - openshift-ansible
    - name: Install glusterfs-fuse
      yum:
        name:
          - glusterfs-fuse
      when:
        - glusterstorage
    - name: Install docker-1.13.1
      yum:
        name:
          - docker-1.13.1
      when: "'lb' not in inventory_hostname"
    - name: create docker-storage-setup file
      copy:
        dest: "/etc/sysconfig/docker-storage-setup"
        content: |
          STORAGE_DRIVER=overlay2
          DEVS={{ device }}
          VG=docker-vg
      when: "'lb' not in inventory_hostname"
    - name: Run  docker-storage-setup
      command: docker-storage-setup
      when: "'lb' not in inventory_hostname"
    - name: install java-1.8.0 packages
      yum:
        name:
        - java-1.8.0-openjdk-devel.x86_64
    when: installpackages
